apiVersion : apps/v1
kind: Deployment
metadata:
  name: cloud-sample 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-sample
  template:
    metadata:
      labels:
        app: cloud-sample 
    spec:
      containers:
        - name: cloud-sample 
          image: acrcloudbizcecomm.azurecr.io/82210667/cloud-sample
          ports:
          - containerPort: 8080
      env:
        - name: SERVER_PORT
          value: "8080"